package main

import (
	"math/rand"
	"time"

	"github.com/bwmarrin/discordgo"
)

var quotes = []string{
	"What fuckin' book?",
	"Can you shoot?",
	"Are you sure, man?",
	"I'm gonna stick. What you got?",
	"You should have run away!",
	"What? Oh, Maccer? He got a little problem he can't control.",
	"Yeah.",
	"Quit it!",
	"Enough, man!",
	"It seems impossible to keep a secret around here! I would have thought the size of the room would keep the numbers down.",
	"Oh, OK, you can stay.",
	"The K's jammed!",
	"OH SHIT!",
	"Hey, what up Z!",
	"...Why?",
	"Z, whatchoo on? Whatever it is, you need to reduce the dosage!",
	"Thank God for that!",
	"Ohhh, Berkley. Who the fuck is Berkley?",
	"Oh, you put hands on him?",
	"Ohhh, I know. You knocked his bitch!",
	"And now he wanna pop you? HAHAHA, and they say gangbangers is petty and small-minded!",
	"Eh what's that bleepin' sound?",
	"Fuck you and your casino!",
	"Fuck you, Ryda'.",
	"Everythang you do is a joke, Ryder.",
	"Ah, so I've heard.",
	"I'm here to bury my Moms. You know that.",
	"Nothing. I live in Liberty City now. I'm clean. Legit.",
	"You know I just got off the plane!",
	"That ain't my gun.",
	"What the fuck you want from me this time?",
	"Whassup, ya'll?",
	"We been putting time in the 'hood, but we gotta get the homies back together, like the old days.",
	"I see what you mean now, man. If crack can do that to Big Bear, turn him into a base slave, the average motherfucker ain't got a chance.",
	"Looks like it's up to us then.",
	"Woozie?",
	"You could at least turn the lights on.",
	"Yeah, this is perfect right here. This is where we're going to plan the heist at.",
	"No.",
	"You gotta have a secret place to plan shit like this, that's just how it's done!",
	"I guess we got to make a plan.",
	"Shit. No. I guess I gotta go get one.",
	"Meeting adjourned.",
	"Now I know you're blind, man - but you gotta see this.",
	"Hear me out on this, homie. All right, the cash room is on the bottom level. There's a bunch of rooms and a tunnel under the whole building with access to the casino floors at either end of the complex. All right? Now,",
	"Oh, my bad - habit.",
	"Yeah, I know.",
	"Hey, hey hey hey! Damn, man - now he's seen the plans!",
	"All right, cool. This is a security card reader that Zero's sent over. Now all we need to do is get one of those cards...",
	"Luckily, there's always one guaranteed weak link in any security set up. The human heart.",
	"Where did you steal your license?",
	"Did you steal your license?",
	"All right, here's the plan. It's all about the art of deception. While I get as much heat on me as possible, y'all get away with the green.",
	"Bingo! Stripes for Mr. Zero here.",
	"So, we're going to steal ourselves an armoured car and re-spray it so it looks like one of their regular trucks.",
	"Exactly what I was thinking. C'mon, come with me, and we're gonna go get some cop wheels...",
	"You get the Packer, hit the Julius Thruway and keep moving.",
	"OK, we got the bikes. And Woozie's taken care of the uniforms. Now, we just gotta get an armoured van and re-spray it with the Caligula's Casino logo.",
	"No, I don't want to get the crew caught up in some street level jacking - it could get ugly.",
	"Shit. I'll fly it, then. We can re-spray it at the airstrip.",
	"Yeah, thanks for that.",
	"Any last requests?",
	"You an asshole to the end. Punk motherfucker.",
	"I don't care 'how', I care 'when'.",
	"As in 'now'. You hear me?",
	"Hey, man, what the - ?",
	"Toreno, fuck you. I almost lost my life out there for you.",
	"Hello?",
	"Aw, Sweet!",
	"All right you hold tight, I'll be right there.",
	"So what was that little job you was talking about, Toreno?",
	"What's the matter? You lost? Need a hand?",
	"Who?",
	"Oh, the bitch. What the hell you want?",
	"Go fuck yourself, you're just they bitch.",
	"Whatever you say, bitch.",
	"Grove Street. Home. At least it was before I fucked everything up.",
	"We switchin' places right now.",
	"Who the fuck is Tommy?",
	"Does the Pope shit in the woods?",
	"Why am I here?",
	"What do you think I'm made of? Puddin'?",
	"No shit.",
	"Woozie, you know I'm black and not Chinese, right?",
	"No. How many?",
	"No.",
	"Man I'm seeing patterns all over the place! Get that smoke out my face.",
	"I'm on it, man, I swear!",
	"Shit, dude, okay! Okay! I swear, man, I'm gonna be the best pilot!",
	"Wait! Please, man!",
	"Cool, what's the problem then?",
	"Aw, shit.",
	"C'mon, dude, what's all that about?",
	"Why?",
	"A what?",
	"Where are you? You givin' me the heebie jeebies, man!",
	"Huh, man, kill Government agents?",
	"That's amazing. You didn't even touch them.",
	"Damn! That nigga's fucked up!",
	"Bang! Bang! Bang!",
	"Who is this?",
	"'Cause you been dealin' drugs, man. Since the age of ten. Ha, ha, ha.",
	"I'm a well-dressed maniac, fool!",
	"'Sup?",
	"You need to lay OFF the coffee!",
	"That's going to my retirement fund",
	"I hope you're clean, bitch.",
	"You don't got no VD or nothing, do ya, bitch?",
	"After five years on the East Coast, it was time to home.",
	"Ah shit, here we go again.",
	"Big smoke! It's me, Carl! Chill, chill!",
	"Seeing my homie. What's up with you?",
	"No homie love? No hug?",
	"'Ey, man, what you strapped for?",
	"I'm always down.",
	"Shit, you crazy! Let's get up outta here!",
	"Look, what was going on, Truth? Who was them dudes?",
	"I'd think you popped another microdot.",
	"After five years on the East Coast, it was time to go home",
	"Ah, they hit a bus!",
	"ahhh G",
	"ahhh, you so kind",
	"Are you a professional moron or just a gifted amateur!",
	"asshole, my shit",
	"Aw, for fuck's sake!",
	"Aw, I wanna immigrate from here!",
	"Aww, you fell off your bike.",
	"cop asshole!",
	"Don't blame me, blame society.",
	"Don't blame me, blame yourself.",
	"Fuck you, po-po!",
	"give me that",
	"Got anything to eat to?",
	"Grab on that is why they call them coffee.",
	"Grab on that is why they call them love handles.",
	"Hey Cesar the Yeh are leaving San Fierro.",
	"Hey, guess what! It's loaded!",
	"Hey, what are you still doing here?",
	"Holy Motherfucker! Where'd you get this!",
	"How are you allowed to drive if you're blind!",
	"I ain't a fat bitch, bitch!",
	"I can't hear anything! I'm DEAF!",
	"I don't want a nightstick up the ass.",
	"I HATE GRAVITY!",
	"I need that shit you drive!",
	"I prefer an ice cream sandwich to coffee.",
	"i tell you what, 1 time, shut your butt.",
	"I was incredible. You were just great.",
	"I'll see you around.",
	"I'm a businessman and this is my business!",
	"I'm going to spend this on a good meal.",
	"I'm gonna get ugly on yo' ass, playa!",
	"I'm rich and I'm fuckin' crazy!",
	"Isn't this what they mean by \"carpool\"?",
	"It's my constitutional right, bitch!",
	"It's the car of my dreams!",
	"just shut up",
	"Lunch money.",
	"Moms, I'm sooo sorry about this.",
	"My car! My fuckin' car!",
	"Never gonna get it, never gonna get it... beyotch!",
	"Not to fast I might have a heart attack!",
	"Now now, you need to exercise more.",
	"Now you can buy a new one!",
	"Now you can buy a new one!",
	"Oh, big surprise, I gotta gun.",
	"Oh, you think I'm a bitch, huh?",
	"Oops, you fell!",
	"Out",
	"Remember, heroes get killed.",
	"SHIT! MAN!... HOW YOU DO THAT?",
	"Shit, glad I don't pay no taxes.",
	"Somebody going to be mad at you for smashing up their vehicle!",
	"Sorry about that. Now fuck off!",
	"That ain't food!",
	"that's very tight",
	"This gonna be easy, bitch!",
	"Toe to toe, fool!",
	"Toreno?",
	"Welcome to America.",
	"Welcome to San Andreas, fool.",
	"What can I say? I'm a bad man.",
	"What did you expect? This is America!",
	"What kind of license you got? Fishin' license?",
	"WHAT THE FUCK?",
	"What's your poison? Grin or gin?",
	"When I was swimming in the ocean once when I was young, I got a condom stuck to my face.",
	"Who let you out of the mental home?",
	"Why won't these guys come after me?",
	"Yeah, maybe we should fall in love or somethin'?",
	"Yeah, regularly.",
	"Yeah, the girl of my dreams, a crack ho.",
	"You a comedian?",
	"You a degenerate?",
	"You callin' CJ a bitch?",
	"You got the car of my dreams!",
	"You hit me! I'm-a hit you back!",
	"You hit my fuckin' ride!",
	"You just ruined your life, asshole!",
	"You okay?... I hope not!",
	"You sure this thing is safe? I can see daylight through the floor.",
	"You wrecked my shit!",
	"you're dick",
}

func commandCJQuote(cm CommandManager, args string, message discordgo.Message, contextual bool) (bool, bool, error) {
	rand.Seed(time.Now().UnixNano())
	quote := quotes[rand.Intn(len(quotes))]
	_, err := cm.App.discordClient.ChannelMessageSend(cm.App.config.PrimaryChannel, quote)
	return true, false, err
}
