version: "3.5"
networks:
  default:
    external:
      name: gateway
  mongodb:
    driver: bridge
    internal: true

services:
  mongodb:
    image: "mongo:${MONGODB_IMAGE_TAG:-3.4}"
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CJ_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: "${CJ_MONGO_PASS}"
    volumes:
      - "${DATA_DIR}/sampcj/mongodb:/data/db"
    networks:
      - mongodb
    labels:
      - traefik.enable=false
  cj:
    image: "southclaws/cj:${CJ_IMAGE_TAG:-latest}"
    restart: on-failure
    environment:
      CJ_MONGO_HOST: ${CJ_MONGO_HOST}
      CJ_MONGO_PORT: ${CJ_MONGO_PORT}
      CJ_MONGO_NAME: ${CJ_MONGO_NAME}
      CJ_MONGO_USER: ${CJ_MONGO_USER}
      CJ_MONGO_PASS: ${CJ_MONGO_PASS}
      CJ_DISCORD_TOKEN: ${CJ_DISCORD_TOKEN:?required}
      CJ_DEFAULT_CHANNEL: ${CJ_DEFAULT_CHANNEL:?required}
      CJ_DEFAULT_ROLE: ${CJ_DEFAULT_ROLE:?required}
      CJ_DEFAULT_COOLDOWN: ${CJ_DEFAULT_COOLDOWN:-180}
      CJ_HEARTBEAT: ${CJ_HEARTBEAT:-60}
      CJ_BOT_ID: ${CJ_BOT_ID:?required}
      CJ_GUILD_ID: ${CJ_GUILD_ID:?required}
      CJ_VERIFIED_ROLE: ${CJ_VERIFIED_ROLE:?required}
      CJ_WIKI_URL: ${CJ_WIKI_URL:-https://github.com/openmultiplayer/web.git}
      CJ_README_CHANNEL: ${CJ_README_CHANNEL:?required}
      CJ_README_GIST_ID: ${CJ_README_GIST_ID:?required}
      CJ_README_GIST_FILE_NAME: ${CJ_README_GIST_FILE_NAME:-samp-discord-rules.md}
      CJ_NO_DATABASE: ${CJ_NO_DATABASE:-false}
      DEBUG: ${DEBUG:-0}
    networks:
      - default
      - mongodb
    depends_on:
      - mongodb
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true
